language: python
python:
  - 2.7
  - 3.3
  - 3.7
  - 3.8
  - pypy
install:
  - pip install -r tools/test-requires --use-mirrors
  - pip install coveralls
  - python setup.py install
script: nosetests --with-coverage
after_success: coveralls
notifications:
  email:
    - dvicente74@gmail.com