language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3
install:
  - pip install -r tools/test-requires
  - pip install coveralls
  - python setup.py install
script: nosetests --with-coverage
after_success: coveralls
notifications:
  email:
    - dvicente74@gmail.com